# Travis CI file, that integrates with coveralls for reporting test coverage.

# This is an example from ADSMasterPipeline -- do not use for affil_match

language: python

python:
  - "3.7"

install:
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

script:
  - "python -m pytest"

after_success:
  - "coveralls"

notifications:
  email: false

sudo: false
