PC_INFILE = 'tests/testdata/pc_dict.txt'
AFFDICT_INFILE = 'tests/testdata/aff_dict.txt'
PICKLE_FILE = 'tests/testdata/aff.pickle'
PICKLE_OUTFILE = 'tests/outputdata/aff.pickle'
UNMATCHED_FILE = 'tests/testdata/unmatched.txt'
DIRECT_RECORDS = 'tests/testdata/records.json'
