"""Create tables

Revision ID: f695622401d6
Revises: 8cc10c3de147
Create Date: 2018-11-06 14:12:13.117957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f695622401d6'
down_revision = '8cc10c3de147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canon',
    sa.Column('aff_id', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('facet_name', sa.String(), nullable=True),
    sa.Column('parents_list', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('children_list', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('aff_id'),
    sa.UniqueConstraint('aff_id')
    )
    op.create_table('string_ids',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('aff_id', sa.String(), nullable=True),
    sa.Column('aff_string', sa.String(), nullable=True),
    sa.Column('orig_pub', sa.Boolean(), nullable=True),
    sa.Column('orig_ml', sa.Boolean(), nullable=True),
    sa.Column('orig_ads', sa.Boolean(), nullable=True),
    sa.Column('ml_score', sa.Numeric(), nullable=True),
    sa.Column('ml_version', sa.String(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_string_ids_aff_id'), 'string_ids', ['aff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_string_ids_aff_id'), table_name='string_ids')
    op.drop_table('string_ids')
    op.drop_table('canon')
    # ### end Alembic commands ###
